# Site
repository: imdhruva/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dhruva Chandra
title: Senior Software Engineer
email: dhruva.sachin@gmail.com
website: https://imdhruva.github.io/resume/
# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  imdhruva
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dhruvachandra
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/self.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Sr. Software Engineer at Splunk who is passionate about delivering cloud native, highly scalable and reliable products which address pressing needs of the business. I enjoy evangalising and realising existing platform. I also enjoy mentoring and growing younger talents.

  I am most skilled in: <mark>AWS</mark>  <mark>Golang</mark>  <mark>Python</mark>  <mark>Terraform</mark>  <mark>GitLab</mark>  <mark>Kubernetes</mark>

content:
  - title: Global DNS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Global DNS @ Splunk
        link: splunk.com
        caption: May 2021 - present
        # link_text: Project Website
        additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The Domain Name Server (DNS) is the Achilles heel of the Web. The important thing is that it's managed responsibly.
        description: | # this will include new lines to allow paragraphs
          I was part of the team that undertook a DNS management tech-debt where we had to :
          * migrate from a specific DNS provider to a custom provider backed with multiple DNS providers
          * design and implement a DNS solution which is cloud-native, micro-services architecture driven, scalable, fault tolerant across regions and eventually consistent across multiple DNS providers.
          * automate and clean dead records (to the tune of ~500K) by scripting jobs that run various validations to make sure the records are not owned any more by Splunk.

          This project involved following technologies:
          <mark>Kubernetes</mark> <mark>Istio</mark> <mark>Prometheus/Grafana</mark> <mark>Micro-services architecture</mark> <mark>Python</mark> <mark>Golang</mark> <mark>AWS</mark> <mark>GCP</mark> <mark>DNS</mark> <mark>Helm</mark> <mark>Gitlab CI</mark> <mark>Terraform</mark>

          This project was seemlessly delivered with zero down time and involved technical leadership in Solution Architecture and maturity and conviction to manage various conflicting decisions along the way.

  - title: Kubernetes Self Service # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Invoice2go
        link: bill.com
        # link_text: boringcompany.com
        sub_title: Senior DevOps Engineer
        caption: May 2020 - May 2021
        quote: >
          An infrastructure engineeer's ultimate goal should be to enable developers to focus on business outcomes
        description: | # this will include new lines to allow paragraphs
            Make a common pattern across organisation to ensure that all the developers in the organisation is self servicable. The outcome of this project was that on creating a code repository a developer is self-services with:
            * CI/CD pipeline
            * Code security scans and test report
            * Registry for container images
            * Deployment manifest (kubernetes manifest)
            * Metrics endpoint and dashboards
            * Monitoring (with SLx dashboards and alerts)
            This involed:
            * Setting up standardising naming conventions across organisations
            * Migrating from Github EE to GitLab EE
            * Setting up linkerd2 cross cluster
            * Setting up cloud native Grafana and Thanos installation on kubernetes
            * standardising EKS upgrades and deployments
            This project increased the scalability of organisation - we can now increase the number of application services without needign to increase hands and feet to enable onboarding. It also meant that developers no more need to have a know-how of how different technolgies work; they just need to know how to use them for their productivity. On implementation this project enhanced the onboarding experience for an app and reduced the number of follow up discussions and tickets by ~80%.
  
  - title: Containerization # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Invoice2go
        link: bill.com
        # link_text: boringcompany.com
        sub_title: Senior DevOps Engineer
        caption: Oct 2019 - May 2020
        quote: >
          DevOps is not just infrastructure engineering. Its a role that evangalizes the platform, develops the platform and enhances the platform
        description: | # this will include new lines to allow paragraphs
            Enahnce the existing setup in Invoice2go from:
            * multi-branch pipelines to single branch pipelines
            * ec2 hosted containers to a proper container orchestration layer
            The vision was to migrate to EKS based kubernetes platform. The scope of project eventually evolved to include:
            * updating multi-branch deployments to main branch deployments
            * standardising deployment patterns. This involves talking to all the stakeholders and classifying different deployments and making a standard pattern across all the organisation for all the deployments
            * creating release management pipelines for secure and CSI complaint AMIs of EKS nodes
            * migrating all containers to EKS via the new deployment engine
            This project involed talking to various stakeholders early on as the platform was being evangalised. Performing demos and roadhows and involve relevant stakeholders in architecture discussions. Performing demos and roadshows for developerds so they remain invested in the new platform. There were regular discussions with developers so the project outcomes stays relevant to the developers. Finally the project delivered near seemless migration of all the application workload in a new deployment pipeline with high developer satisfaction and productivity.
  
  - title: SRE # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Splunk
        link: splunk.com
        # link_text: boringcompany.com
        sub_title: SRE
        caption: May 2019 - Oct 2019
        # quote: >
        #   DevOps is not just infrastructure engineering. Its a role that evangalizes the platform, develops the platform and enhances the platform
        description: | # this will include new lines to allow paragraphs
            Assist in migrating thousands of SplunkCloud customers to a new version of Splunk software with object backed storage. This project involved working at massive scale to make sure migration process with multiple touchpoints is completely automated, seemless and massively scalable. It involved scripting in Golang, writing custom terraform modules, coordinating with multiple teams and mentoring folks to upskill in coding and AWS.
  
  - title: Sr Consultant # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sr Infrastructure Consultant
        link: https://www.cmdsolutions.com.au/
        # link_text: boringcompany.com
        sub_title: Sr Infrastructure Consultant
        caption: May 2018 - May 2019
        quote: >
          This was the biggest learning curve for me as we were invested in creating cookie-cutter patterns for various start-ups to make sure they get highly compliant AWS landing zones up in a matter of hours rather than days.
        description: | # this will include new lines to allow paragraphs
            Did multiple projects on AWS to migrate customers from on-premise. This involed following technolgies and competence:
            * Python
            * AWS
            * PCI-DSS complaice
            * APRA compliance
            * Ansible, Puppet, Terraform
            This gig really tought me:
            * how to manage expectations on a project
            * how to keep colleagues invested and motivated in projects
            * keep projects relevant to a customers needs
            * importance of enjoying time with colleagues

  - title: Consultant # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Consultant @ Qantas
        link: https://www.qantas.com.au/
        # link_text: boringcompany.com
        sub_title: Consultant
        caption: Jan 2010 - May 2018
        # quote: >
        #   This was the biggest learning curve for me as we were invested in creating cookie-cutter patterns for various start-ups to make sure they get highly compliant AWS landing zones up in a matter of hours rather than days.
        description: | # this will include new lines to allow paragraphs
            Started my tenure with on-prem Middleware technologies, and sloly progressed to manage multiple Middleware technologies including:
            * WebLogic Servers
            * Web Servers
            * MQ Servers
            * SOA Suite

            Eventually I was busy with PoC on AWS for cost saving opportunities which is when I started working in _Center of Excelence for Cloud_. Where I was part of the team which built Qantas Cloud Platform - an ecapsulation over a public Cloud with other enabling technologies wrapped in including:
            * Atlassian Suite
            * Proxy servers
            * Splunk
            * CSI compliant AMIs
            * AD Services
            * Content Management Platform, etc.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amrita University
        caption: 2006 - 2010
        sub_title: BTech Electronics & Instrumentation
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at the university I learnt a lot about control systems and eletronics. I also had the opportunity to work in [Indian Institute of Astrophysics](https://www.iiap.res.in/) to develop a hub to collect temperature variances within the telescope.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Adventure sports ([bungy jumping](https://youtu.be/ADC9OhDJFIg?t=41), skydiving, [scuba diving](images/scuba.jpg) )
      - Swimming
      - [Hiking](images/royal_arch.jpg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
